name: build-docs
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  release:
    types: [created]
jobs:
  deploy:
    runs-on: python:3
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: pip3 install mkdocs-material mike
      - name: Build dev docs
        if: contains(github.ref, 'develop')
        run: mike deploy --push dev
      - name: Build latest release docs
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          RELEASE_VERSION=${GITHUB_REF#refs/tags/}
          mike deploy --push --update-alias $RELEASE_VERSION latest
